{
  "formatVersion": "1.1",
  "component": {
    "url": "../../live-sdk/0.1.0/live-sdk-0.1.0.module",
    "group": "io.github.gycrosskit",
    "module": "live-sdk",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "live-sdk-iosSimulatorArm64Main-0.1.0.klib",
          "url": "live-sdk-iossimulatorarm64-0.1.0.klib",
          "size": 175991,
          "sha512": "aa4e43e05d7dda33d7eafc6f2564609ee5a4e7d5f22d2c2d82c39367cb17daedbb26b0578605207dea3bc0a4ea651a8fb1b5c908ed79f9998536f3a89e3b3ddf",
          "sha256": "c23010e5e952fc3eacdb7138935aeb95b522183dddbcfd0a802e12f24be6d46a",
          "sha1": "5914c94816960528c2fcda82cb2c0b0f2d156a8d",
          "md5": "f33fbcb1743734d440e9a36381796b2f"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "live-sdk-iossimulatorarm64-0.1.0-sources.jar",
          "url": "live-sdk-iossimulatorarm64-0.1.0-sources.jar",
          "size": 30899,
          "sha512": "e854d0080fbdb9535deb7495b36d07362b1aecaa96682c9db349865b0dce92aa253ed2aba2492b7462874aeccbe8f18ea23419f9fa618174603f15fe797ed758",
          "sha256": "a9d22fa63e7c25d9387d3990c96ec791ec90bd9bbb44bcf528f04a0cdc8e4a14",
          "sha1": "2c43db3d06b873b6f511d0d80355850939a3ee07",
          "md5": "3db80e80603d920329bfcaf01f78a10f"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "live-sdk-0.1.0.kotlin_resources.zip",
          "url": "live-sdk-iossimulatorarm64-0.1.0-kotlin_resources.kotlin_resources.zip",
          "size": 346,
          "sha512": "62883ad967328ef6355059e684db4ce4367dfcc331e86dbff413262adfc62c927ea4ee8d2455e23141f521b9ac209888ab417501df2ddb5aab455e5e463870df",
          "sha256": "61d96047b67f7652d8b14ea102a011ec218db823f9df7d36a911960625d7cd78",
          "sha1": "4f4818854e1cb4c8062935e92ca90a8f0ef9b430",
          "md5": "22e99fa84d10f690250af187ccb2050c"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "live-sdk-iossimulatorarm64-0.1.0-metadata.jar",
          "url": "live-sdk-iossimulatorarm64-0.1.0-metadata.jar",
          "size": 8175,
          "sha512": "59d9f3e15bbfce2ef9d95db7de120e66c3462a36cb73d9b10cfe5cf892c843bdf0382e01d6dfcc39cc99b1b54e23fac10a598baa4badc8bc953846536c06a50d",
          "sha256": "50b042439ea4c4c99e2b50a55ac844fe978ef6a837dcaad186b1ba6fd4ee5cdf",
          "sha1": "9a7795b5c22d17de171abdfa3cea82861a7841e7",
          "md5": "151ffe412f74ccc5faf3fbd0bd73d8f0"
        }
      ]
    }
  ]
}
