{
  "formatVersion": "1.1",
  "component": {
    "url": "../../live-sdk/0.1.0/live-sdk-0.1.0.module",
    "group": "io.github.gycrosskit",
    "module": "live-sdk",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "live-sdk-iosArm64Main-0.1.0.klib",
          "url": "live-sdk-iosarm64-0.1.0.klib",
          "size": 175925,
          "sha512": "f2f4d7645d1b077b99d7692776b160082fbb6c662957d8b872c3824004748da05be780b4515f2744a6a944683aa49a7c762905036277cc36378026eaf0f96d22",
          "sha256": "11acb88c1be1a9386aa3fec54f0fca117b2790b549f1849e6497ddd2cecee8e9",
          "sha1": "80e71f901d799be2dc608cdbc5b6ca3eee5d53b4",
          "md5": "8825c03db9b580fab4bb301a1a774c2a"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "live-sdk-iosarm64-0.1.0-sources.jar",
          "url": "live-sdk-iosarm64-0.1.0-sources.jar",
          "size": 30899,
          "sha512": "e854d0080fbdb9535deb7495b36d07362b1aecaa96682c9db349865b0dce92aa253ed2aba2492b7462874aeccbe8f18ea23419f9fa618174603f15fe797ed758",
          "sha256": "a9d22fa63e7c25d9387d3990c96ec791ec90bd9bbb44bcf528f04a0cdc8e4a14",
          "sha1": "2c43db3d06b873b6f511d0d80355850939a3ee07",
          "md5": "3db80e80603d920329bfcaf01f78a10f"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "live-sdk-0.1.0.kotlin_resources.zip",
          "url": "live-sdk-iosarm64-0.1.0-kotlin_resources.kotlin_resources.zip",
          "size": 346,
          "sha512": "4be10e24a18750a8242cb2e0820e7b529189cb2e72e390e2f3cf25983607d79764d7220b05d499d20bf22fd60ff4440b943418ed03774885e55306c15e059be6",
          "sha256": "2249e02bd7c9f617e3a6ef7829d051582a578294e53c9b89afdc89c5d9668aee",
          "sha1": "af88afd557577cbaac19300ff00071453534eb8a",
          "md5": "8901c08d3c0c699ce9409db9c3371ec0"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "live-sdk-iosarm64-0.1.0-metadata.jar",
          "url": "live-sdk-iosarm64-0.1.0-metadata.jar",
          "size": 8175,
          "sha512": "59d9f3e15bbfce2ef9d95db7de120e66c3462a36cb73d9b10cfe5cf892c843bdf0382e01d6dfcc39cc99b1b54e23fac10a598baa4badc8bc953846536c06a50d",
          "sha256": "50b042439ea4c4c99e2b50a55ac844fe978ef6a837dcaad186b1ba6fd4ee5cdf",
          "sha1": "9a7795b5c22d17de171abdfa3cea82861a7841e7",
          "md5": "151ffe412f74ccc5faf3fbd0bd73d8f0"
        }
      ]
    }
  ]
}
